"""splent_feature_about

Revision ID: 6df2da62ffd8
Revises:
Create Date: 2026-08-12 14:14:17.673196

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6df2da62ffd8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "about_section",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("published", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_about_section_slug"), "about_section", ["slug"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_about_section_slug"), table_name="about_section")
    op.drop_table("about_section")
    # ### end Alembic commands ###
